"""
Django settings for sysmo project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import logging
import configparser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# LOG_PATH = "/var/log/sysmo/"
LOG_PATH = ""
# CONFIG_PATH = "/etc/sysmo/"
CONFIG_PATH = ""
AP_CONF = CONFIG_PATH + "server.conf"

ap_cp = configparser.RawConfigParser()
ap_cp.read(AP_CONF)
# Server 設定參數
# Log 相關參數
DEFAULT_INTERVAL: int = int(ap_cp.get('LOGROTATE', 'INTERVAL'))
CPU_POLICY: dict = {
    "Pass": 0,
    "Warning": int(ap_cp.get('CPU_POLICY', 'CPU_WARNING')),
    "Major": int(ap_cp.get('CPU_POLICY', 'CPU_MAJOR')),
    "Critical": int(ap_cp.get('CPU_POLICY', 'CPU_CRITICAL'))
}
MEM_POLICY: dict = {
    "Pass": 0,
    "Warning": int(ap_cp.get('MEMORY_POLICY', 'MEM_WARNING')),
    "Major": int(ap_cp.get('MEMORY_POLICY', 'MEM_MAJOR')),
    "Critical": int(ap_cp.get('MEMORY_POLICY', 'MEM_CRITICAL'))
}
SWAP_POLICY: dict = {
    "Pass": 0,
    "Warning": int(ap_cp.get('SWAP_POLICY', 'SWAP_WARNING')),
    "Major": int(ap_cp.get('SWAP_POLICY', 'SWAP_MAJOR')),
    "Critical": int(ap_cp.get('SWAP_POLICY', 'SWAP_CRITICAL'))
}

DISK_POLICY: dict = {
    str(ap_cp.get('DISK_POLICY', 'DISK_MOUNTPOINT')): {
        "Pass": 0,
        "Warning": int(ap_cp.get('DISK_POLICY', 'DISK_WARNING')),
        "Major": int(ap_cp.get('DISK_POLICY', 'DISK_MAJOR')),
        "Critical": int(ap_cp.get('DISK_POLICY', 'DISK_CRITICAL'))
    }
}

# Mail 相關參數
MAIL_SWITCH: int = int(ap_cp.get('MAIL', 'SWITCH'))
MAIL_HOST: str = ap_cp.get('MAIL', 'HOST')
MAIL_PORT: int = int(ap_cp.get('MAIL', 'PORT'))
MAIL_USE_TLS: str = ap_cp.get('MAIL', 'USE_TLS')
MAIL_USER: str = ap_cp.get('MAIL', 'USER')
MAIL_PASSWORD: str = ap_cp.get('MAIL', 'PASSWORD')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j3(h@5!8=!jq_m4l%hl3cuj1)vduym9#vg2d748jq$7_6t#ls3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

logging.basicConfig(
    level=logging.INFO if DEBUG is False else logging.DEBUG,
    filename=LOG_PATH + "sysmo.log",
    # format = '%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s',
    format='%(asctime)s %(levelname)s %(name)s : %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S')
logging.info("Setting Reloaded.")

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1', '192.168.1.105']
LIST_PER_PAGE = 20

# Application definition

INSTALLED_APPS = [
    'logserver.apps.LogserverConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_extensions',
    # 'debug_toolbar',
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
}

# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.timer.TimerPanel',
#     'debug_toolbar.panels.headers.HeadersPanel',
#     'debug_toolbar.panels.request.RequestPanel',
#     'debug_toolbar.panels.sql.SQLPanel',
#     'debug_toolbar.panels.cache.CachePanel',
#     'debug_toolbar.panels.logging.LoggingPanel',
# ]

ROOT_URLCONF = 'sysmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sysmo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "logserver",
        'USER': "root",
        'PASSWORD': "1qaz@WSX",
        'HOST': "127.0.0.1",
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = 'asserts/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
