# Generated by Django 4.1.7 on 2023-03-29 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logserver.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('hostname', models.CharField(max_length=40, verbose_name='主機名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('ruuid', models.CharField(max_length=40, unique=True, verbose_name='RUUID')),
                ('network_info', models.JSONField(verbose_name='網路資訊')),
                ('disk_info', models.JSONField(verbose_name='硬碟資訊')),
                ('cpu_info', models.JSONField(blank=True, null=True, verbose_name='CPU資訊')),
                ('mem_info', models.JSONField(blank=True, null=True, verbose_name='記憶體資訊')),
                ('os_info', models.JSONField(blank=True, null=True, verbose_name='作業系統資訊')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='策略名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cpu_policy', models.JSONField(default=logserver.models.policy_default, verbose_name='CPU策略')),
                ('mem_policy', models.JSONField(default=logserver.models.policy_default, verbose_name='MEM策略')),
                ('swap_policy', models.JSONField(default=logserver.models.policy_default, verbose_name='SWAP策略')),
                ('disk_policy', models.JSONField(blank=True, null=True, verbose_name='Disk策略')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CPU')),
                ('mem_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MEM')),
                ('swap_usage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SWAP')),
                ('disk_usage', models.JSONField(blank=True, null=True, verbose_name='Disk')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logserver.machine', verbose_name='主機')),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='群組名稱')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinegroups', to='logserver.policy', verbose_name='群組策略')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='logserver.machinegroup', verbose_name='主機群組'),
        ),
        migrations.AddField(
            model_name='machine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='擁有者'),
        ),
    ]
