# Generated by Django 4.1.7 on 2023-03-16 09:59

from django.db import migrations, models
import logserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0002_remove_machinegroup_machines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cpupolicy',
            field=models.JSONField(default=logserver.models.policy_default, verbose_name='CPU策略'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='mempolicy',
            field=models.JSONField(default=logserver.models.policy_default, verbose_name='MEM策略'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='swappolicy',
            field=models.JSONField(default=logserver.models.policy_default, verbose_name='SWAP策略'),
        ),
    ]
