# Generated by Django 4.1.7 on 2023-03-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0003_alter_policy_cpupolicy_alter_policy_mempolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logserver.machinegroup', verbose_name='主機群組'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hostname',
            field=models.CharField(max_length=40, verbose_name='主機名稱'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='Gpolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logserver.policy', verbose_name='群組策略'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='群組名稱'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='策略名稱'),
        ),
    ]
